fourkitchens/sous-drupal-project

sous/Starter.php
Fixes the issue -
Receiving error when install is performing theme install:
`sh: line 0: cd: web/themes/contrib/emulsify-design-system/: No such file or directory`
- Closes: https://www.drupal.org/project/sous/issues/3199022
=> fix: correct path for emulsify install

.lando.yml, composer.json
- Updates lando config to php 7.4
- https://en.wikipedia.org/wiki/PHP
- PHP 7.4 is the latest and last major version of PHP7. It will be supported until the end of 2022.
- PHP 7.4 is the default version of PHP on drupal specific hosts like Acquia and Pantheon so issues with compatibility shouldn't be a concern.
=> feat: Update php to 7.4

sous/Starter.php
- Sets the admin theme to Claro during install. See: https://github.com/fourkitchens/sous-drupal-distro/pull/25
=> feat: set the admin theme to claro

package.json
- fix: missing commands
This commit accidentally wiped out the package.json commands: https://github.com/fourkitchens/sous-drupal-project/commit/600ec91995188c170fab8aa620f9fde84e2f61d8, this PR adds them back.
=> fix: missing commands

sous/Starter.php
This PR does the following:
- Removed support for the [Claro Admin theme](https://www.drupal.org/project/claro/)
- Installs the [Gin admin theme](https://www.drupal.org/project/gin)
- Notes:
- Gin is a new core theme with a rigorously tested design system: https://www.drupal.org/docs/8/core/themes/gin-theme/design.
- Accessibility is a driving focus of gin.
- The color palette is fairly neutral.
- Support and bug fixes will be bundled with core updates.
=> Change the admin theme to Gin and remove Claro

composer.json
To remove the drupal/console dependency composer.json since it is no longer used.
=> fix: remove drupal console

composer.json
To include oomphinc to the allow-plugins tree in composer.json.
Create the project as you normally would with `composer create-project`. You should no longer see the following during the creation process:
```
oomphinc/composer-installers-extender contains a Composer plugin which is b  
locked by your allow-plugins config. You may add it to the list if you cons  
ider it safe.                                 
You can run "composer config --no-plugins allow-plugins.oomphinc/composer-i  
nstallers-extender [true|false]" to enable it (true) or disable it explicit  
ly and suppress this exception (false)                    
See https://getcomposer.org/allow-plugins
```
=> fix: adds oomphinc to allow-plugins

README.md
Add instructions to let the user know that they need to manually type in the "drupal9" password in order to install the database.
=> Add database password instructions

composer.json, sous/Starter.php
- Simplify the install process by automatically updating the lando site name and default config folder. Fixes this process for linux-based OS's.
- Run the following command on MacOS and Linux-based OS: `composer create-project fourkitchens/sous-drupal-project:dev-fix-sed-command-for-linux super-awesome-drupal-site --no-interaction` and confirm there are no errors returned.
=> fix: distro version and find-and-replace command for linux

composer.json
**Purpose**
- Sets up composer.json to use the `file-mapping` rather than the old `initial` key.
- Removes all line entries that `core-composer-scaffold` copies over by default.
- Adds new entry to copy over example settings to local settings. This is set up as `overwrite: false` so it is not overwritten once it is configured.
**DO Issue**
[https://www.drupal.org/project/sous/issues/3325717](https://www.drupal.org/project/sous/issues/3325717)
**Functional Testing**
- Checkout this branch.
- Perform a composer install e.g. `lando composer install`
- Ensure proper files are copied over.
- Edit the settings.local.php file.
- Run composer install again
- Recognize that the settings.local.php file is not overwritten.
=> 3325717: Setup settings.local.php and scaffold it during initial install

assets/scaffold/files/additions-default.settings.txt, assets/scaffold/files/additions-example.settings.local.txt, composer.json, web/.gitignore
- Adds new additions file that includes a hash salt and db credentials for local development.
- Updates composer file-mapping scaffolding to append database credentials and hash salt.
- Updates composer file-mapping to copy example.settings.local.php to settings.local.php.
- Updates additions file for default.settings.php to include file_exists code block so out of the box our local settings file will be used.
NOTES:
- I added the hash salt because I received a hash salt missing error.
- We are successfully appending database credentials to `example.settings.local.php` during scaffolding. However this file is scaffolded to `web/sites/example.settings.local.php`. When trying to scaffold `example.settings.local.php` to `settings.local.php`, I would get an error stating the file at …
=> Settings scaffold

config/default/core.extension.yml, config/default/gin.settings.yml, sous/Starter.php
- Enables Gin Toolbar so the FE theme is consistent with the Admin theme
- Removed references to the old sous-profile during the theme-setup step
- Set some reasonable Gin settings for horizontal toolbar and 4K green accent
- run `composer create-project fourkitchens/sous-drupal-project:dev-remove-profile-set-gin-admin-theme-cleanup test-sous-remove --no-interaction --ignore-platform-reqs` 
- Once the above is complete `cd` into your new project directory and run `lando start`
- Verify you can go through the entire Drupal install process without error
- Verify you can see the Gin Toolbar while viewing the FE theme
- Verify the toolbar is horizontal and green accent color
=> Cleanup of Gin Theme integration PR

.lando.yml, composer.json, config/default/core.extension.yml, scripts/sous/setup.sh
- disable composer process timeout
- enable media library, which we should use instead of entity builder for media
- add npm install at beginning of sous setup script
Disable composer process timeout is because while running the sous setup script from the remove-profile-legacy-modules branch, I got this error:
Note: I am seeing an error with husky when running npm install
I'm getting this error with the emulisify init step:
It fails after this step (continues to run but a lot of npm errors). But if I cd into the directory and run the steps that are in that script manually, it works. 
Test using:
Run the following command to setup your new Drupal site - `composer create-project fourkitchens/sous-drupal-project:dev-remove-profile-legacy-modules-timeout test-sous-project --no-interaction …
=> disable composer process timeout and enable media library

composer.json
[Issue](https://www.drupal.org/project/sous/issues/3347277)
=> feat: Add patches for field validation when tabs are on edit form

config/default/core.extension.yml, config/default/editor.editor.full_html.yml, config/default/filter.format.full_html.yml, config/default/user.role.superuser.yml
DO Issue: https://www.drupal.org/project/sous/issues/3377848
The entity browsers appeared to already be removed. So I uninstalled the entity_browser modules and enabled and did a basic config for core media library. Let me know if there is a particular way you want this configured.
=> 3377848-remove-media-entity

.lando.yml
[Issue](https://www.drupal.org/project/sous/issues/3385967)
[Error](https://app.warp.dev/block/bzLalVWjtgpM39K9tXHsVw)
Nodesource Node have new features and now the 
_Installation Scripts: The installation scripts setup_XX.x are no longer supported and are not needed anymore, as the installation process is straightforward for any RPM and DEB distro._
So I change the way to install this according to the new propose mentioned in their repo readme.
=> Install issue with nodesource.

scripts/sous/setup.sh
- Corrects the setup scripts label for the custom theme it generates
=> fix: update setup theme label

composer.json
- Removes git repository references to Emulsify dev versions. This is now installed/handled by the Sous-Emulsify recipe - https://github.com/fourkitchens/sous-emulsify
=> fix: Remove dev repos for the new version of Emulsify

scripts/sous/theme-build.sh
During the initial project setup it's typical to also setup the CI process. This process triggers the `npm run theme-build` command for remote environments. However, the project doesn't yet have a component library installed so any theme-build attempts cause a failure.
=> feat: Allow theme-build command to fail gracefully

patches/composer.patches.json
- This patch has been rolled into the latest release of field_group and no longer applies
=> fix: remove field_group patch because it has been merged

.ddev/commands/web/emulsify, .ddev/config.yaml
- Closes #121 
- Fixes DDEV architecture
- Adds DDEV support for emulsify-cli command
- [SOUS-60: DDEV NPM error when installing Emulsify Theme](https://app.clickup.com/t/36718269/SOUS-60)
=> SOUS-60: DDEV NPM error when installing Emulsify Theme
